# Generated by Django 2.0.2 on 2018-03-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descriptcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('descriptcion', models.CharField(max_length=500)),
                ('destinos', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='boleto_basico',
            fields=[
                ('boleto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.boleto')),
                ('Nombreb', models.CharField(default='Boleto basico', max_length=30)),
            ],
            bases=('home.boleto',),
        ),
        migrations.CreateModel(
            name='boleto_oro',
            fields=[
                ('boleto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.boleto')),
                ('Nombreb', models.CharField(default='boleto oro', max_length=30)),
            ],
            bases=('home.boleto',),
        ),
        migrations.CreateModel(
            name='boleto_vip',
            fields=[
                ('boleto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.boleto')),
                ('NOmbreb', models.CharField(default='boleto vip', max_length=30)),
            ],
            bases=('home.boleto',),
        ),
        migrations.CreateModel(
            name='ticket_actividad',
            fields=[
                ('boleto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.boleto')),
                ('Nombreta', models.CharField(max_length=30)),
                ('Dias', models.CharField(max_length=30)),
                ('horarios', models.CharField(max_length=30)),
            ],
            bases=('home.boleto',),
        ),
        migrations.CreateModel(
            name='ticket_restaurante',
            fields=[
                ('boleto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.boleto')),
                ('Nombretr', models.CharField(max_length=30)),
                ('restaurante', models.CharField(max_length=30)),
            ],
            bases=('home.boleto',),
        ),
        migrations.AddField(
            model_name='boleto',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ruta'),
        ),
    ]
