# Generated by Django 2.0.2 on 2018-03-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_compra_subscriptores'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptores',
            name='nombre',
            field=models.CharField(default='nombre', max_length=30),
            preserve_default=False,
        ),
    ]
