# Generated by Django 2.0.2 on 2018-03-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_subscriptores_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptores',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
